### ISSUE TITLE
Add "resolve qcode" generic helper function instead of qcode->uri functions in each class

### ISSUE THREAD

**Issue by bquinn** [iptc/python-newsmlg2#1]
Currently we have a function get_uri() to look up a qcode in the catalog and resolve it to a URI:
```
(Pdb) item = document.get_item()
(Pdb) item.itemmeta
<NewsMLG2.anyitem.ItemMeta object at 0x104f36cd0>
(Pdb) item.itemmeta.itemclass
<NewsMLG2.itemmanagement.ItemClass object at 0x104f825b0>
(Pdb) item.itemmeta.itemclass.qcode
'cinat:scheme'
(Pdb) item.itemmeta.itemclass.get_uri()
'http://cv.iptc.org/newscodes/cinature/scheme'
```

At today's call we decided that it would be best to only expose the raw elements and attributes through the main code, but to also include a helper function to resolve qcodes to URIs generically.

So people could do:
```
(Pdb) resolve_qcode(item.itemmeta.itemclass.qcode)
'http://cv.iptc.org/newscodes/cinature/scheme'
```

**Comment by comandantefer037-jpg** [comment]
> Actualmente tenemos una función get_uri() para buscar un qcode en el catálogo y resolverlo en una URI:
> 
> ```
> (Pdb) item = document.get_item()
> (Pdb) item.itemmeta
> <NewsMLG2.anyitem.ItemMeta object at 0x104f36cd0>
> (Pdb) item.itemmeta.itemclass
> <NewsMLG2.itemmanagement.ItemClass object at 0x104f825b0>
> (Pdb) item.itemmeta.itemclass.qcode
> 'cinat:scheme'
> (Pdb) item.itemmeta.itemclass.get_uri()
> 'http://cv.iptc.org/newscodes/cinature/scheme'
> ```
> 
> En la llamada de hoy decidimos que sería mejor exponer únicamente los elementos y atributos sin procesar a través del código principal, pero también incluir una función auxiliar para resolver qcodes en URI de manera genérica.
> 
> Así que la gente podría hacer:
> 
> ```
> (Pdb) resolve_qcode(item.itemmeta.itemclass.qcode)
>  [




](#'http://cv.iptc.org/newscodes/cinature/scheme')
> ```
